### ISSUE TITLE
Please add support for Phidget 1065 DC Motor Controller

### ISSUE THREAD

**Issue by NCharabaruk** [ccny-ros-pkg/phidgets_drivers#11]
Hello,

Would it be possible for you to add support for the Phidget 1065 DC motor driver to this package?

Thanks

**Comment by muhrix** [comment]
@NCharabaruk have you got any further with implementing `PhidgetMotorControl` compatibility? Thanks!

**Comment by NCharabaruk** [comment]
I forgot about this. I wound up using [phidgets-ros-pkg](http://wiki.ros.org/phidgets) and modifying the Motor Control HC node for my uses.

**Comment by muhrix** [comment]
Thanks for replying! I'm afraid I don't have such a device to develop the driver, otherwise I would do it.
