### ISSUE TITLE
Diagnostics package integration?

### ISSUE THREAD

**Issue by kkiyenga** [ccny-ros-pkg/phidgets_drivers#19]
Hey,

Do you think adding some diagnostics from the diagnostics package would be worthwile for the phidgets drivers?

http://wiki.ros.org/diagnostics

Thanks,

**Comment by kkiyenga** [comment]
I have an idea as to how to implement the diagnostics.

**Comment by muhrix** [comment]
Hi @kklyenga,

All suggestions for improvement are welcome!

What kind of diagnostics information would you have in mind for the `phidgets_drivers` package?

**Comment by kkiyenga** [comment]
Cool, maybe something like connection status? Also some diagnostics on the topic could also be done.

Just some ideas.

Thanks,

**Comment by kkiyenga** [comment]
You think this is a good idea to have for phidgets?

Keshav

**Comment by muhrix** [comment]
Hi,

I think that diagnostics on the connection would be a welcome feature. Regarding the topics, it depends on what sort of diagnostics could be useful.

**Comment by kkiyenga** [comment]
Ok, I will try to get this working (just connection diagnostics) and do a pull request by this week.

**Comment by muhrix** [comment]
Since PR #20 has been merged, I am closing this issue. Thanks a lot for your contribution @kkiyenga!
