### ISSUE TITLE
update README to refer to ROS indigo

### ISSUE THREAD

**Issue by dogoepp** [ccny-ros-pkg/phidgets_drivers#21]
The title of the README on indigo branch refers to ROS Groovy/Hydro but i believe this branch is about Indigo. Could you please update this ?

**Comment by mintar** [comment]
Yes, I guess the best way is to remove the distro-specific wording altogether (otherwise we cannot have branches for different distros point to the same commit). I've opened a pull request. @muhrix , please merge.

**Comment by dogoepp** [comment]
No one to accept the pull request of @mintar ?

**Comment by dogoepp** [comment]
Thanks a lot :)
