### ISSUE TITLE
The "phidgets_imu" package is not  getting orientation from the IMU and its returning a null vector instead

### ISSUE THREAD

**Issue by Jasmin92** [ccny-ros-pkg/phidgets_drivers#26]
In the ROS wiki , they said that
 "The raw IMU data. Includes linear accelerations and angular velocities, but **_does not**_ include orientation."
And the node is returning a null orientation vector, why it's not returning the orientation?

**Comment by mintar** [comment]
If you want the orientation, you need to use an imu filter such as [imu_filter_madgwick](http://wiki.ros.org/imu_filter_madgwick). An example can be found in [phidgets_imu/launch/imu.launch](https://github.com/ccny-ros-pkg/phidgets_drivers/blob/bed081632b99672bfaebfb3da4f6ed320d294982/phidgets_imu/launch/imu.launch).

**Comment by Jasmin92** [comment]
I will , thank you @mintar .
