### ISSUE TITLE
phidgets_imu should publish MagneticField, not Vector3

### ISSUE THREAD

**Issue by mintar** [ccny-ros-pkg/phidgets_drivers#29]
`phidgets_imu` currently publishes magnetometer information as `geometry_msgs/Vector3Stamped`. We should switch to `sensor_msgs/MagneticField` instead, because it's the appropriate message.

The best way to do the switch without interrupting users would be to keep Indigo as it is, and do the switch starting from Jade. It's an easy fix, but we need a jade branch before doing a PR. Perhaps this could be combined with #28 (so merge #28 into Jade, not Indigo).

**Comment by muhrix** [comment]
Good point. The question is whether we want to have `jade` and `kinetic` branches within this repo, or to add `phidgets_drivers` to `ros_drivers` and continue development there (eventually this repo would be "discontinued").

**Comment by mintar** [comment]
Migrating to `ros_drivers` would be great. I think the next step would be post a message to the Discourse [release category](http://discourse.ros.org/c/release) asking if they are interested in hosting `phidgets_drivers`. It's a mature and relatively widely used repo, so give it a shot.

It would be ideal if @idryanov gave us owner permissions, so we could actually *move* the repo. But I think that's not going to happen, so copying the repo to `ros_drivers` would be the next best solution.

**Comment by mintar** [comment]
Never mind, I've merged this into jade: https://github.com/ros-drivers/phidgets_drivers/commit/656ec9f47562babc79ec48379bc472e028fe8494
